version: '3'
services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        ports:
            - "8000:8000"
        volumes: 
            - ./:/var/www/html
        environment: 
            MYSQL_DATABASE: todo
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
    
    db:
        image: mysql:5.7.31
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: todo
            MYSQL_ROOT_PASSWORD: secret